# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LiveSplit
email: info@livesplit.org
description: > # this means to ignore newlines until "baseurl:"
  A sleek, highly-customizable timer for speedrunners.
baseurl: "" # the subpath of your site, e.g. /blog
imagesurl: "/images"
url: "http://livesplit.github.io" # the base hostname & protocol for your site
cryze_username: CryZe107
wooferzfg_username: wooferzfg
livesplit_username: LiveSplit

# Build settings
markdown: kramdown
exclude: [vendor, Gemfile, Gemfile.lock, LICENSE]
